[build]
  command = "npm run build"    # Replace with your build command
  publish = "dist"            # Replace with the folder containing your built files

[build.environment]
  # Add any environment variables needed during build, e.g., NODE_ENV, API_KEY, etc.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
