[build]
  command = "npm run build"    # Replace with your build command
  publish = "dist"            # Replace with the folder containing your built files

[build.environment]
  AGENT_ID = "f3ca579f-4cef-421e-94b1-258c647819f3"
  DF_PROJECT_ID = "grecords-357114"
  DF_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDWsvnI2oi6nff8
SoEBxWWxzG0GFtVRRln0npMKjsgqD25Lvxq/AEGz7iXsWL7XQkE6S2C1u0vvcP5g
0LxWxBePM7rZ0zl6uUqYbmUkiM0qQ4w5XwRThRPf+r5VXigB3p87n86ugbce4aXD
6nwHf1D3hK9FbcsR/S72w1ghgGc2hwp73T4b33ceM89TkhVVwnLsNNjFCO7/UsYI
I3BpSms/icvK9z7njc1nVN5rvi/3DYjMtq406ZJA8al0r81p7PfVjX31WKdDPGw9
s4AuL1OO2FraLZfp2t6YpEbXYNAJs/49LCL4Rr9PfL5qgLTGjWo8x66F7J0hcIi5
yDEJ02SNAgMBAAECggEABumiIWLTN6pPOiGI9/kL05bDejMhK6R8+s4MlHCxRlS9
sPUmeTiwJN5Zp2YvwNJaiMlgBAHo3uelB7zOGj9mix8NLfxpyPHZ0mttg2i0gwmZ
OcioJOtE5EzYX3sbBSe5Oewk4AP/qiAgRvJQC4AV0okEXqh7Zb5137k9khiRBNWd
pUQ/TMaQrQe0uTeffIWP+6fdu4jVPUjb1KwdM0+eEiQgWsKte7A2nlCj6JqRWlfo
J1545dwkKYb8SqqF7dd16j8gonObPSVbf3mMB7zNQigG+ugAssubMDbdvASvnh97
ojFa7UVF03CGzcBeQfSOYpbAUT3qzZHZjUDg+7L76QKBgQDqnKa2BlzGU+elxAeM
kqGDxii7ztVBGPDyaanWxo9kmlxaZ+myn6Nd23Tc+t5qEOL9Q4OF3n38UBzIrIDP
9w4FJNUgBD+lz6TyHhi4yw5N0GviIzBlIJGu1NF+yw57fi78ke7qF5jKqULDxlrc
+MQqVCfNXQ5lVHjYYvGxf6nAmQKBgQDqRZoMVSPiFgbq0OwQDJ0Yxq+mGSUTyUXr
LAjOXo85BfLQgdWjsTCDPNKKxK4oUok8xkKal8m4DWKQXgyQPBOzv97FDluO4fPy
k4ryGTva+QSc/4q1QzKu7BsYf7A/W2SaQsWf2ED0xnSWsEJaRFH/yEu71WuiQJwJ
Db1TUYJYFQKBgEDz3bPHTygZUqix/OUOM2koE17rhF7haNO0LTEpB8nycl8VJb4u
NCxn9ZK4YZs70ZwMdP06++Y+x7lHCOKKo3cJG3ghtP1S33eonW+LyAoDCdsxotRc
j/i3MsjHrtrBtIB4Zoyou8Rf1/wbjkxfEvAlHF/ew32KRWqi+gcKMRUBAoGASwkW
CUMv5hdGCen24kEYBDqHQf0lyguakH
-----END PRIVATE KEY-----"""
  DF_PRIVATE_KEY_ID = "4ed790bf56537c73d67a016c4f0be0d09d7ec084"
  DF_CLIENT_EMAIL = "covidbot-test-account@grecords-357114.iam.gserviceaccount.com"
  MONGODB_URL = "mongodb+srv://test:test@mongo-test.kadf8.mongodb.net/appointment?retryWrites=true&w=majority"
  MAIL_TRAP_USER = "2cea5e7fc13300"
  MAIL_TRAP_PASS = "a075b1c318ac16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
